In [1]:
#multi input channels
import d2lzh as d2l
from mxnet import nd

In [4]:
def corr2d_multi_in(X, K):
    return nd.add_n(*[d2l.corr2d(x, k) for x, k in zip(X, K)])

In [5]:
X = nd.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
K = nd.array([[[0, 1], [2, 3]], [[1, 2], [3, 4]]])

corr2d_multi_in(X, K)


[[ 56.  72.]
 [104. 120.]]
<NDArray 2x2 @cpu(0)>

In [7]:
#multi output channels
def corr2d_multi_in_out(X, K):
    return nd.stack(*[corr2d_multi_in(X, k) for k in K])

In [8]:
K = nd.stack(K, K + 1, K + 2)
K.shape

(3, 2, 2, 2)

In [9]:
corr2d_multi_in_out(X, K)


[[[ 56.  72.]
  [104. 120.]]

 [[ 76. 100.]
  [148. 172.]]

 [[ 96. 128.]
  [192. 224.]]]
<NDArray 3x2x2 @cpu(0)>

In [17]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    print('c_i %d h %d w %d' %(c_i, h, w))
    c_o = K.shape[0]
    print('c_o %d'%( c_o))
    X = X.reshape((c_i, h * w))
    print(X)
    K = K.reshape((c_o, c_i))
    print(K)
    Y = nd.dot(K, X)  # 全连接层的矩阵乘法
    return Y.reshape((c_o, h, w))

In [18]:
X = nd.random.uniform(shape=(3, 3, 3))
K = nd.random.uniform(shape=(2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)

(Y1 - Y2).norm().asscalar() < 1e-6

c_i 3 h 3 w 3
c_o 2

[[0.32504722 0.57019675 0.03842543 0.43860152 0.63427407 0.9883738
  0.95894927 0.10204481 0.6527903 ]
 [0.20887676 0.6350589  0.16130951 0.9952996  0.6531083  0.58185035
  0.2532916  0.4143686  0.46631077]
 [0.4746975  0.2444256  0.6235101  0.15896958 0.33800763 0.11037514
  0.6747523  0.6563296  0.31720173]]
<NDArray 3x9 @cpu(0)>

[[0.13818295 0.77834547 0.19658236]
 [0.9495711  0.36872518 0.66252685]]
<NDArray 2x3 @cpu(0)>


True

In [19]:
Y1


[[[0.3008114  0.6211364  0.25343534]
  [0.8665448  0.6624361  0.6111548 ]
  [0.4623032  0.46564558 0.51551163]]

 [[0.7001734  0.9375431  0.5090587 ]
  [0.8887969  1.067045   1.2262005 ]
  [1.4510269  0.68452287 1.001966  ]]]
<NDArray 2x3x3 @cpu(0)>

In [20]:
Y2


[[[0.3008114  0.6211364  0.25343537]
  [0.8665448  0.6624361  0.6111548 ]
  [0.46230322 0.4656456  0.51551163]]

 [[0.7001734  0.93754303 0.5090588 ]
  [0.8887969  1.067045   1.2262006 ]
  [1.4510269  0.68452287 1.001966  ]]]
<NDArray 2x3x3 @cpu(0)>