In [1]:
from mxnet import autograd, nd
from mxnet.gluon import nn

In [17]:
def corr2d(X, K):
    h, w = K.shape
    print('X:')
    print(X)
    print('K:')
    print(K)
    print('K.shape:')
    print(K.shape)
    Y = nd.zeros((X.shape[0] -h +1, X.shape[1] -w +1))
    print(Y)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            print('i = %d j = %d h = %d w = %d' %(i, j, h, w))
            Y[i, j] = (X[i:i + h, j:j +w] * K).sum()
    return Y

In [18]:
X = nd.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
K = nd.array([[0, 1], [2, 3]])

corr2d(X, K)

X:

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)>
K:

[[0. 1.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>
K.shape:
(2, 2)

[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>
i = 0 j = 0 h = 2 w = 2
i = 0 j = 1 h = 2 w = 2
i = 1 j = 0 h = 2 w = 2
i = 1 j = 1 h = 2 w = 2



[[19. 25.]
 [37. 43.]]
<NDArray 2x2 @cpu(0)>