In [1]:
from mxnet import autograd, nd

In [2]:
#print(dir(autograd))

In [3]:
#create data set
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = nd.random.normal(scale=1, shape=(num_examples, num_inputs))
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += nd.random.normal(scale=0.01, shape=labels.shape)

In [4]:
from mxnet.gluon import data as gdata

In [5]:
#print(dir(gdata))

In [6]:
#get dataset
batch_size = 10
dataset = gdata.ArrayDataset(features, labels)
data_iter = gdata.DataLoader(dataset, batch_size, shuffle=True)

In [7]:
for X, y in data_iter:
    print(X, y)
    break


[[ 0.70900095 -0.37375227]
 [-0.8720539   0.6916261 ]
 [-1.1014541  -0.41594216]
 [-0.18023393  0.68018126]
 [ 0.04628786  0.48509744]
 [ 0.82003313 -0.74541706]
 [-1.436299   -1.2416507 ]
 [ 1.6947968  -0.28610373]
 [ 0.54093814  0.05206425]
 [-1.2240661   0.4964614 ]]
<NDArray 10x2 @cpu(0)> 
[6.9013777  0.09408624 3.4144146  1.5309746  2.6319473  8.348353
 5.559958   8.553605   5.1196246  0.05394617]
<NDArray 10 @cpu(0)>


In [8]:
#define model
from mxnet.gluon import nn

In [9]:
#print(dir(nn))

In [10]:
net = nn.Sequential()

In [11]:
net.add(nn.Dense(1))

In [12]:
#init model parameters
from mxnet import init

In [13]:
#print(dir(init))

In [14]:
net.initialize(init.Normal(sigma=0.01))

In [15]:
#define loss function
from mxnet.gluon import loss as gloss

In [16]:
#print(dir(gloss))

In [17]:
loss = gloss.L2Loss()

In [18]:
#define optimize function
from mxnet import gluon

In [19]:
#print(dir(gluon))

In [20]:
trainer = gluon.Trainer(net.collect_params(), 'sgd', {'learning_rate':0.03})

In [21]:
num_epochs = 3
for epoch in range(1, num_epochs+1):
    for X, y in data_iter:
        with autograd.record():
            l = loss(net(X), y)
        l.backward()
        trainer.step(batch_size)
    train_l = loss(net(features), labels)
    print('epoch %d, loss %f' %(epoch, train_l.mean().asnumpy()))

epoch 1, loss 0.040749
epoch 2, loss 0.000152
epoch 3, loss 0.000050


In [22]:
dense = net[0]
true_w, dense.weight.data()

([2, -3.4], 
 [[ 1.999286  -3.3997877]]
 <NDArray 1x2 @cpu(0)>)

In [23]:
true_b, dense.bias.data()

(4.2, 
 [4.199932]
 <NDArray 1 @cpu(0)>)

In [25]:
#print(net)

In [31]:
dense.weight.data().grad


[[-0.00034857 -0.01903494]]
<NDArray 1x2 @cpu(0)>

In [ ]:
dense.weight.data().grad